linkedin_task:
  description: >
    Search for a person on LinkedIn and return their profile information.
  expected_output: >
    A list of the person's profile information.
  agent: linkedin_scraper
