get_my_profile:
  description: >
    Retrieve my LinkedIn profile information using the my_linkedin_url from the inputs.
    Generate a detailed professional profile with all relevant information.
    Make sure to include full name, current position, company, location, industry,
    skills, work experiences, education history, and certifications.
  expected_output: >
    A structured profile object containing all professional details including
    work experience, education, skills, and certifications.
  agent: linkedin_scraper_my_profile

get_contact_profile:
  description: >
    Retrieve the contact's LinkedIn profile information using the contact_linkedin_url from the inputs.
    Generate a detailed professional profile with all relevant information.
    Make sure to include full name, current position, company, location, industry,
    skills, work experiences, education history, and certifications.
  expected_output: >
    A structured profile object containing all professional details including
    work experience, education, skills, and certifications.
  agent: linkedin_scraper_contact_profile

webscraping_event:
  description: >
    Scrape the event content on the web using {event_url}.
    Be sure to provide the event data including title, date, organization, 
    leader or speaker or instructor, URL, and content.
    You must store the event data in the required format
    and accurate response to the user without assumption.
  expected_output: >
    The event content from the webpage should be provided.
    The event data is in JSON format.
  agent: event_researcher
