get_my_profile:
  description: >
    Retrieve my LinkedIn profile information using the my_linkedin_url from the inputs.
    Generate a detailed professional profile with all relevant information.
    Make sure to include full name, current position, company, location, industry,
    skills, work experiences, education history, and certifications.
  expected_output: >
    A structured profile object containing all professional details including
    work experience, education, skills, and certifications.
  agent: linkedin_scraper_my_profile

get_contact_profile:
  description: >
    Retrieve the contact's LinkedIn profile information using the contact_linkedin_url from the inputs.
    Generate a detailed professional profile with all relevant information.
    Make sure to include full name, current position, company, location, industry,
    skills, work experiences, education history, and certifications.
  expected_output: >
    A structured profile object containing all professional details including
    work experience, education, skills, and certifications.
  agent: linkedin_scraper_contact_profile

webscraping_event:
  description: >
    Scrape the event content on the web using {event_url}.
    Be sure to provide the event data including title, date, organization, 
    leader or speaker or instructor, URL, and content.
    You must store the event data in the required format
    and accurate response to the user without assumption.
  expected_output: >
    The event content from the webpage should be provided.
    The event data is in JSON format.
  agent: event_researcher

analyze_and_create_messages:
  description: >
    Analyze both LinkedIn profiles and event information to:
    1. Identify key similarities and connections between the profiles (skills, industry, education, etc.)
    2. Find relevant talking points based on the event context
    3. Create a personalized LinkedIn connection request message (max 300 characters)
    4. Draft a detailed follow-up email that expands on the connection points and suggests collaboration opportunities
  expected_output: >
    A JSON object containing:
    - List of key similarities and connection points
    - LinkedIn connection request message
    - Follow-up email draft
    - Suggested talking points for future interaction
  agent: profile_analyzer

format_and_save_message:
  description: >
    Take the connection message generated by the profile analyzer and format it into a
    professional markdown document. The document should include:
    1. A header with the contact's name and the event name
    2. The LinkedIn connection message (formatted for easy copying)
    3. The follow-up email draft
    4. Key talking points and similarities identified
    Save this formatted content in the messages directory with an appropriate filename
    based on the contact's name and event.
  expected_output: >
    A confirmation message indicating the markdown file has been created successfully,
    including the file path where it was saved.
  agent: message_formatter
